.\" Man page for the client.

.TH CLIENT 1 "17 décembre 2017" 1.0

.SH NAME
client \- récupère un hash ou indique en posséder un à un serveur

.SH SYNOPSIS
.B ./client
.I IP
.I PORT
.I COMMANDE
.I HASH
.I [IP]

.SH DESCRIPTION
Quand COMMANDE vaut PUT, le client indique au serveur accessible par IP et PORT
qu'il possède le fichier désigné par le hash HASH. Quand COMMANDE vaut GET,
il indique qu'il veut récupérer le fichier dont le hash est passé en argument,
et récupère l'adresse IP du client en possession du hash.

.\" Valeurs de retour à ajouter

.SH OPTIONS
Aucune option n'est supportée par le programme actuellement.
.\" Limitations à ajouter

.SH SEE ALSO
server(1)

.SH BUGS
Ce programme est encore en cours de développement.

.SH AUTHOR
Ludovic Muller,
Méline Bour-Lang
